### PR TITLE
Newsweek Clone - Microverse Project Submission

### PR DESCRIPTION
**Pull request by umairarshadbutt**
Newsweek Clone - Microverse Project Submission

### CODE REVIEW

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Status: Changes required 🛑

## Hi team 👋. Such a remarkable project you made 🧨👌! Awesome README 💯 !

### However we need to work on some changes before we can move ahead. Let's see:

- The top nav section must also follow the "space on either side" rule, just like other elements.

#### Clone
image

#### Original
image

- Please fix this 👇
image

- The bottom-left tag on the magazine cover in `in the magazine` section is missing.

#### Clone
Annotation 2020-07-01 013302

#### Original
Annotation 2020-07-01 013321

- The height of the magazine is larger than the other articles. Also, increase the size of the `card-image-position` element so that the space between the two rows could be decreased.

#### Clone
Annotation 2020-07-01 013550

#### Original
Annotation 2020-07-01 013522

- Decrease its font-size 👇

Annotation 2020-07-01 014112

- Please fix the misalignment 👇
Annotation 2020-07-01 014235

#### Original
Annotation 2020-07-01 014256

- Please remove the bottom border
Annotation 2020-07-01 014413

#### Original
Annotation 2020-07-01 014438

- Please change the footer logo to match the original

#### Clone
image

#### Original
image

- Please fix this part 👇
Annotation 2020-07-01 014740

- Please fix this 👇
Annotation 2020-07-01 014841

#### Original
image

Apply these changes and request another review.

Happy coding 👨‍💻

**Review by rammazzoti2000 — CHANGES_REQUESTED** [review]
### Hello [@umairarshadbutt, @Alexoid1] :wave: 
You did great job on this one, massive use of bootstrap classes, HTML code is semantic enough, the readme file is descriptive (great mockups), and also most of the changes required by the previous TSE have been implemented, except a few.
Anyway, based on that and on some other issues I must ask you the following changes before moving on :point_down: 

### :stop_sign: Required Changes :construction: :construction_worker: 
### Large Screen
- [x] The `Subscribe` & `Newsletter` sections still need some work to do, you can notice the height of the two sections is not matching, also as requested by previous TSE, the newsweek logo must match the one from the original website
### Original
image
### Clone
image
- [x] As soon as I am resizing the page the navbar shows this bad behaviour where the elements from the left are being pushed to the center, also the links are wrapping on a new row and the search input is overflowing outside its container, which again is a bad behaviour.
image

### Medium Screen
- [x] The main `Trending` navbar is still showing, while on the original page is not, also the main content is using only part of the width of the screen, see the picture bellow :point_down: 
### Original 
image
### Clone
image
- [x] Again the page behaviour when on breakpoint at 992px is not the same as the original, compare your project against the original one to see the differences, footer included.

### Small Screen
- [x] The page behaviour is not the same as the one of the original one when on breakpoint 768px, please compare your page against the original one at that breakpoint

### <em>Kindly fix the REQUIRED issues and send another code review request.

Cheers and Happy coding! :clap: 

Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of **_alexandru_** if you have any additional question)</em>
### :stop_sign: Status: Required Changes

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status requires changes :recycle: 
## hello guys great job so far :clap: :tophat:, but I have :warning:  noticed that you didn't do the required changes :recycle:  by the previous TSE @rammazzoti2000, please return back to his [review](https://github.com/umairarshadbutt/News-Week-Clone/pull/1#pullrequestreview-440449915) and do the required changes before you request another code review.

please do that otherwise we will not be able to approve your project

### Please make the required changes before you request another code review.
## Happy Coding :tophat: 
_If you are stick at any point or you have questions don't hesitate to contact me on slack, I will be happy to help_

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status requires changes :recycle: 
## hello guys great job so far :clap: :tophat:, but I have :warning:  noticed that you didn't do the required changes :recycle:  by the previous TSE @rammazzoti2000, please return back to his [review](https://github.com/umairarshadbutt/News-Week-Clone/pull/1#pullrequestreview-440449915) and do the required changes before you request another code review.

please do that otherwise we will not be able to approve your project

### Please make the required changes before you request another code review.
## Happy Coding :tophat: 
_If you are stick at any point or you have questions don't hesitate to contact me on slack, I will be happy to help_

**Review by elmejdki — APPROVED** [review]
# status approved :heavy_check_mark: 
## Great job guys thank you for making the required changes. :tophat: 

now you can merge to master your project is approved.

## Happy Coding.

**Pull request merged**
